@ECHO OFF
IF "%1" ==  "" GOTO ARG1NUL
SET TARGET=%1
GOTO TEND
:ARG1NUL
SET TARGET=MBOOT
:TEND

D:\MASM\MASM.EXE %TARGET%.ASM, ,%TARGET%.LST;
ECHO START /B /WAIT D:\MASM\LINK.EXE %TARGET%.OBJ, %TARGET%.EXE, %TARGET%.MAP;
D:\MASM\LINK.EXE %TARGET%.OBJ, %TARGET%.EXE, %TARGET%.MAP;

ECHO :WAITTARGET
ECHO IF NOT EXIST %TARGET%.EXE GOTO WAITTARGET
EXE2BIN %TARGET%.EXE %TARGET%.IMG

DEL %TARGET%.OBJ
DEL %TARGET%.EXE
DEL %TARGET%.MAP
ECHO DEL %TARGET%.EXE

ECHO w 0100 0 0 1 >Debug.txt
ECHO q >>Debug.txt

DEBUG %TARGET%.IMG < DEBUG.TXT
REM DEBUG BOOT.BIN < DEBUG.TXT
ECHO DEBUG %TARGET%.IMG ^< DEBUG.TXT
DEL Debug.txt
ECHO ON
