REM 设置LCC-WIN 3.2 的环境路径
REM 运行本文件后,使用如下方法编译FILE.C文件
REM LCC -c -g2 -S -I%%LCCINC%% -L%%LCCLIB%% <FILE.C>
REM 使用如下方法连接FILE.OBJ
REM LCCLNK -subsystem console -o <FILE.EXE> FILE.OBJ $(LIBS)
IF NOT "%LCCINC%" == "" GOTO END
SET PATH=D:\LCC\BIN;%PATH%
SET LCCINC=D:\LCC\INCLUDE
SET LCCLIB=D:\LCC\LIB
:END