@ECHO OFF
@REM 设置Borland C++ 5.0 的环境路径
@REM 运行本文件后,使用如下方法编译FILE.C文件
@REM BCC32 -v -I%%BC5INC%% -L%%BC5LIB%% FILE.C

@IF NOT "%BC5BASE%" == "" GOTO END
@SET BC5BASE=D:\BC5
@SET PATH=%BC5BASE%\BIN;%PATH%
@SET BC5INC=%BC5BASE%\INCLUDE
@SET BC5LIB=%BC5BASE%\LIB

:END
@ECHO ON
