#!/bin/sh
# Displays a truncated long listing (ll) and 
# displays size statistics
# of the files in the listing.

ls -l $* | \
awk	'
BEGIN {
x=i=0; printf "%-25s%-10s%8s%8s\n", "FILENAME", "OWNER", "SIZE", "TYPE" 
}

$1 ~ /^[-dlps]/ {			# line format for nomal files
	printf "%-25s%-10s%8d", $8, $3, $5
	x = x + $5
	i++
}
$1 ~ /^-/ { printf "%8s\n", "file" }	# standard file types
$1 ~ /^d/ { printf "%8s\n", "dir"  }
$1 ~ /^l/ { printf "%8s\n", "link" }
$1 ~ /^p/ { printf "%8s\n", "pipe" }
$1 ~ /^s/ { printf "%8s\n", "socket" }
$1 ~ /^[bc]/ { 				# line format for device files
	    printf "%-25s%-10s%8s%8s\n", $8, $3, "0", "dev" }
END {
	printf "The files listed occupy %d bytes (%f Mbytes)\n", x, x / 1024 / 1024
	printf "Average file size is %d bytes\n", x / i
}
'

