UINT code index_html_len = 2583;
char code index_html[] = {
"<HTML><HEAD><TITLE>堈最諷秶</TITLE><META http-equiv=refresh content=10>\n"
"<SCRIPT LANGUAGE=JAVASCRIPT>\n"
"function getswitch() {\n"
"	var newval, i, mask;\n"
"\n"
"	mask = 0x01;\n"
"	newval = 0;\n"
"	for (i = 0; i < 8; i++) {\n"
"		if (switch_sel(2 * i).checked) {\n"
"			newval +=  mask;\n"
"		}\n"
"		mask <<= 1;\n"
"	}\n"
"	document.forms(0).switch_result.value = \"\" + newval;\n"
"	document.forms(0).submit();\n"
"	return true;\n"
"}\n"
"\n"
"function body_load(){\n"
"	var newval, i, mask;\n"
"\n"
"	newval = document.forms(0).switch_result.value;\n"
"	mask = 0x01;\n"
"	for (i = 0; i < 8; i++) {\n"
"		if (newval & mask) {\n"
"			switch_sel(2 * i).checked = true;\n"
"		} else {\n"
"			switch_sel(2 * i + 1).checked = true;\n"
"		}\n"
"		mask <<= 1;\n"
"	}\n"
"	return true;\n"
"}\n"
"</SCRIPT>\n"
"</HEAD>\n"
"<BODY onload='javascript:body_load();'>\n"
"<TABLE width=780>\n"
"<tr><td colspan=2>\n"
"<H1> <IMG height=74 src=photo1.jpg width=305></H1>\n"
"<H1>數呾儂悝埏</H1>\n"
"&nbsp&nbsp;&nbsp;<FONT size=4>堈最諷秶栳尨厙珜</FONT>\n"
"</td></tr>\n"
"\n"
"<tr><td>\n"
"<TABLE width=419 border=0>\n"
"<TR>\n"
"<TD width=120>LED1</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s1>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s1>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED2</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s2>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s2>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED3</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s3>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s3>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED4</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s4>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s4>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED5</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s5>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s5>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED6</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s6>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s6>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED7</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s7>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s7>做 \n"
"</TD>\n"
"</TR>\n"
"<TR>\n"
"<TD width=120>LED8</TD>\n"
"<TD width=150>\n"
"<INPUT type=radio id=switch_sel  value=1 name=s8>謠 \n"
"<INPUT type=radio id=switch_sel  value=0 name=s8>做 \n"
"</TD>\n"
"</TR>\n"
"</TABLE>\n"
"</td></tr>\n"
"\n"
"<tr><td>\n"
"<FORM action=/index.html method=POST>\n"
"<INPUT type=hidden id=switch_result name=switch value=TAG:CHK2>\n"
"<INPUT type=button value=楷冞 onclick='javascript:return getswitch()'>\n"
"</FORM>\n"
"</td></tr>\n"
"</TABLE>\n"
"\n"
"</BODY></HTML>\n"
};
